# SPDX-FileCopyrightText: 2019 Florian Müllner <fmuellner@gnome.org>
#
# SPDX-License-Identifier: MIT OR LGPL-2.0-or-later

extends:
 - ./gnome-shell-extensions/lint/eslintrc-gjs.yml
 - ./gnome-shell-extensions/lint/eslintrc-shell.yml
