image: bastien/deploy

deploy:
  script:
    - git remote add github git@github.com:BastienDurel/rdesktop-menu.git || true
    - git pull origin master
    - git fetch origin
    - git push --mirror github
  tags:
    - docker
