image: localhost:5000/deploy

deploy:
  script:
    - git remote add github git@github.com:BastienDurel/rdesktop-menu.git || true
    - git pull origin master
    - git fetch origin
    - git push github
  tags:
    - docker

build:
  script: zip -j rdesktop-menu@bastien.git.geekwu.org.zip *.js metadata.json README.md example.conf
  artifacts:
    paths:
      - rdesktop-menu@bastien.git.geekwu.org.zip
    expire_in: 1 year
