image: localhost:5000/deploy
variables:
  GIT_SUBMODULE_STRATEGY: recursive

deploy:
  stage: deploy
  script:
    - git clone https://git.geekwu.org/bastien/rdesktop-menu.git
    - cd rdesktop-menu/
    - git push --mirror git@github.com:BastienDurel/rdesktop-menu.git
  tags:
    - docker

build:
  stage: build
  image: node:latest
  script:
    - npm install
    - make lint
    - apt update && apt install -y zip
    - make package
  artifacts:
    paths:
      - rdesktop-menu@bastien.git.geekwu.org.zip
    expire_in: 1 year
