image: localhost:5000/deploy

deploy:
  stage: deploy
  script:
    - git for-each-ref --format 'delete %(refname)' refs/pull | git update-ref --stdin
    - git for-each-ref --format 'delete %(refname)' refs/pipelines | git update-ref --stdin
    - git push --mirror git@github.com:BastienDurel/rdesktop-menu.git
  tags:
    - docker

build:
  stage: build
  script: zip -j rdesktop-menu@bastien.git.geekwu.org.zip *.js metadata.json stylesheet.css README.md example.conf
  artifacts:
    paths:
      - rdesktop-menu@bastien.git.geekwu.org.zip
    expire_in: 1 year
